// Public static pages; keep in sync with App Router page files.
export const staticRoutes = [
  "/cookies",
  "/disclaimer",
  "/privacy",
  "/terms",
  "/blog",
  "/capabilities",
  "/contact",
  "/faq",
  "/get-started",
  "/infrastructure-technology-operations",
  "/internships",
  "/locations",
  "/",
  "/partners",
  "/pillars",
  "/products",
  "/services",
  "/solutions/dell-business-laptops",
  "/solutions/engineering-workstation-package",
  "/solutions/microsoft-365-migration",
  "/solutions/new-employee-technology",
  "/solutions/new-office-it-setup",
  "/solutions",
  "/solutions/projectwise-health-check",
  "/solutions/small-business-startup-package",
  "/tools-and-utilities",
  "/topics",
  "/who-we-support",
  "/why-civicspan"
] as const
